@startuml containers

    [Фронтенд]
    [Главный сервис]
    [БД пользователей]

    [Сервис статистики]
    [ClickHouse]

    [Сервис постов и комментариев]
    [БД постов]
    [БД комментариев]

    [Фронтенд] --> [Главный сервис] : REST API
    [Главный сервис] --> [БД пользователей] : Хранение
    [Главный сервис] --> [Сервис статистики] : gRPC
    [Главный сервис] --> [Сервис постов и комментариев] : gRPC

    [События просмотров и лайков] --> [Брокер сообщений]

    [Брокер сообщений] --> [Сервис статистики] : События

    [Сервис статистики] --> [ClickHouse] : Хранение

    [Сервис постов и комментариев] --> [БД постов] : Хранение
    [Сервис постов и комментариев] --> [БД комментариев] : Хранение

@enduml