@startuml context
actor User as User
    User --> (Регистрация)
    User --> (Авторизация)

    (Регистрация) --> (Авторизация) : При успешной регистрации
    (Авторизация) --> (Просмотр своей стены) : При успешной авторизации
    (Авторизация) --> (Просмотр стен других пользователей) : При успешной авторизации
    (Просмотр своей стены) --> (Добавление поста)
    (Просмотр своей стены) --> (Редактирование поста) : Кнопка Редактировать
    (Просмотр своей стены) --> (Удаление поста) : Кнопка Удалить
    (Просмотр стен других пользователей) --> (Оценка поста) : Кнопка Лайк
    (Просмотр стен других пользователей) --> (Добавление комментария к посту) : Кнопка Добавить комментарий
@enduml
