@startuml context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Контекст

Person(registered_user, "Зарегистрированный пользователь")
Person(not_registered_user, "Незарегистрированный пользователь")

System(self_wall, "Своя стена")
System(other_wall, "Стены других пользователей")

Rel(registered_user, self_wall, "Добавляет свои посты")
Rel(registered_user, other_wall, "Просматривает посты, добавляет комментарии")
Rel(not_registered_user, other_wall, "Просматривает посты")

@enduml
